### ISSUE TITLE
Navigatiemogelijkheid uitbreiden: van interview naar persoon of thema

### ISSUE THREAD

**Issue by ocrasborn** [ocrasborn/doofgewoon#10]
- Door de grote hoeveelheid interviews zullen mensen af en toe de weg kwijt zijn. Zorgen dat er bij elke video een link komt naar de overzichtspagina van die persoon, en naar de overzichtspagina van het thema waar dit interview bijhoort. Hoe dit elegant op te lossen, liefst met beeld? Door plaatjes van persoonspagina en thema klein weer te geven onder de video, maar boven de Uitweiding?

**Comment by signfuse** [comment]
gebeurd

**Comment by signfuse** [comment]
Eerste aanzet is gebeurd.
