### ISSUE TITLE
Menu-item "?" hernoemen naar "Waarom deze site?"

### ISSUE THREAD

**Issue by ocrasborn** [ocrasborn/doofgewoon#11]

**Comment by signfuse** [comment]
Menu breekt hierdoor sneller af, maar daarvoor is volgens mij wel al een andere issue.
Opmerking: Designgewijs heeft deze tekst een langere streep nodig dan de rest. Storend of niet? Kortere tekst voorzien?

**Comment by ocrasborn** [comment]
Tja, lastig. Ik vind het vooralsnog niet storend, laten we even kijken wat anderen zeggen. Omdat er zo'n behoefte aan is, die pagina, vind ik het niet zo'n goeie optie om alleen "Waarom?" over "Over" te gebruiken. Weet jij een korter alternatief?
