### ISSUE TITLE
Externe hyperlinks standaard in nieuw tabblad; interne links in huidige window laden

### ISSUE THREAD

**Issue by ocrasborn** [ocrasborn/doofgewoon#13]

**Comment by signfuse** [comment]
Dit moet toegepast worden in de HTML code, door het toevoegen van de tekst `target="_blank"` binnen de `<a>` tag. In de engine van doofgewoon worden volgens mij geen externe links behandeld, enkel in de handgeschreven html toevoegingen. Ik kan dit voor jou aanpassen, maar lees eerst even verder.

Bv:
`De Vlaamse website <a href="http://www.mijnbabyisdoof.be">Mijn baby is doof</a>`
wordt
`De Vlaamse website <a href="http://www.mijnbabyisdoof.be" target="_blank">Mijn baby is doof</a>`

Maar! Er is enige controverse rond dit geforceerd laden in een nieuw tabblad, zeker onder de techies;
https://duckduckgo.com/?q=should+links+open+in+a+new+window&t=ffsb&ia=web

Daartegenover doet Facebook het wel, wat de overslag in de hand kan werken. Google doet het zelden en Wikipedia nooit.

Wat denk je?

**Comment by signfuse** [comment]
Ik las ergens dat het voor slechtzienden en blinden storend is als een nieuw tabblad geopend wordt. Misschien weet Yassine meer?

**Comment by ocrasborn** [comment]
Dat geloof ik meteen, maar mensen kunnen zelf ook per link er voor kiezen om het wel hetzelfde window te openen. Ik denk dat het voor andere bezoekers veel overzichtelijker wordt, dus graag toch doen.

**Comment by signfuse** [comment]
Ik zie wel hoe ik kan kiezen om een link in een nieuw venster kan openen (rechtermuisklik), maar niet om het in hetzelfde venster te openen? Hoe doe je dat?

**Comment by ocrasborn** [comment]
Hm, ja, ik dacht dat dat altijd in het context-menu zat. Ik heb even zitten lezen bij bovenstaande link, en ben toch wel overtuigd: beter controle aan de gebruiker laten, en dus niet nieuwe tabs/windows opleggen
