### ISSUE TITLE
Safezone

### ISSUE THREAD

**Issue by signfuse** [ocrasborn/doofgewoon#18]
In bijlage bestanden om de safezone te bepalen.

Voorbeeld:
![safezone_sample](https://cloud.githubusercontent.com/assets/19531551/15930085/37543f5a-2e51-11e6-9e89-d60fac13670f.png)

Transparant bestand in png (om over je foto's te leggen) - kan in elk programma geopend worden:
![safezone](https://cloud.githubusercontent.com/assets/19531551/15930086/3754af80-2e51-11e6-806f-0440cab7faaf.png)

Transparant bestand voor photoshop:
[safezone.psd.zip](https://github.com/ocrasborn/doofgewoon/files/306909/safezone.psd.zip)

**Comment by ocrasborn** [comment]
Ik ga er mee stoeien, dankjewel
