### ISSUE TITLE
Menu-balk breekt soms af

### ISSUE THREAD

**Issue by ocrasborn** [ocrasborn/doofgewoon#2]
Onduidelijk wanneer; i.i.g. in Safari af en toe

**Comment by signfuse** [comment]
Aangepast voor verlengde menubalk tgv 'Waarom deze site' ipv '?'
_Te heropenen wanneer dit opnieuw breekt_

**Comment by signfuse** [comment]
Breekt in safari op http://doofgewoon.nl/?q=interview/180
