### ISSUE TITLE
Tweetalige ondertitels

### ISSUE THREAD

**Issue by ocrasborn** [ocrasborn/doofgewoon#21]
Kunnen we in één VTT-bestand meerdere talen opnemen? Of is er een aparte uploadknop nodig voor een Engels VTT-bestand? We gaan niet alles tweetalig doen, maar wel een aantal.

**Comment by signfuse** [comment]
Ja, voor ondertitels moet dit apart (met talige identifier). Heb uploadknop gemaakt.
Ik moet wel nog de code aanpassen zodat ze ook wordt weergegeven op de video, dat volgt later nog (samen met de andere ondertitel-issues). 
Maar je kan gerust al uploaden hoor.

**Comment by ocrasborn** [comment]
In onze workflow van ELAN > SRT (via export) > VTT (via srt-to-vtt command line script) wordt deze talige identifier nergens toegevoegd, hoe ziet hij er precies uit?

**Comment by signfuse** [comment]
Die is er voor zover ik weet niet... In de html code wordt identifier
toegevoegd afhankelijk van welke uploadknop je gebruikt
Op 13 jun. 2016 12:46 schreef "ocrasborn" notifications@github.com:

**Comment by ocrasborn** [comment]
Ah, zo — perfect voor ons!!
