### ISSUE TITLE
Max. videoupload staat op 2MB

### ISSUE THREAD

**Issue by ocrasborn** [ocrasborn/doofgewoon#25]
Ook iets door de drupalupdate? Weet je trouwens zeker dat dat gebeurd was, die update? Want dan moet ik daar nog even achteraan, dat ze de volgende keer ons waarschuwen.

**Comment by signfuse** [comment]
Het enige wat ik zeker weet is dat het bestand gewijzigd was. Mijn
conclusie daaruit is een update, maar om zeker te zijn vraag je best even
aan Wessel.

Ik heb zelf wel enkele dagen op voorhand een bericht gekregen van drupal
zelf dat er een probleem was met hun product en dat een update aanbevolen
was. Ik denk dat het team bij RU dat advies gevolgd heeft.

Wat betreft de filesize voor upload, dat is waarschijnlijk gerelateerd. Ik
heb het weer aangepast, hopelijk is het weer goed nu.

Sven
Op 20 jun. 2016 00:40 schreef "ocrasborn" notifications@github.com:
