### ISSUE TITLE
Thema-lijst compacter maken

### ISSUE THREAD

**Issue by ocrasborn** [ocrasborn/doofgewoon#5]
Downscalen opdat er vier rijen naast elkaar staan; kleiner lettertype geen probleem

**Comment by ocrasborn** [comment]
- Wat mij betreft mag de thema-foto bovenaan ook wel iets kleiner, die neemt nu veel ruimte in, terwijl de inhoud (lijst thema's) pas op ong. 1/3e van het scherm begint. Liever iets uitzoomen waardoor evt. links/rechts een witte balk verschijnt, dat valt niet op door de witte achtergrond van de foto's en dan blijft toch nog iets van het gebaar zichtbaar.

**Comment by signfuse** [comment]
is aangepast. Kan wel nieuwe issues opleveren. Graag melden als nieuwe issue.

**Comment by ocrasborn** [comment]
beter zo!
