### ISSUE TITLE
Welkom-filmpje op homepage weergeven

### ISSUE THREAD

**Issue by ocrasborn** [ocrasborn/doofgewoon#9]
- en uploadbaar maken natuurlijk, ergens
- optie om na eerste weergave te verbergen, waarna huidige homepage met rotating interviews verschijnt

**Comment by signfuse** [comment]
Er wordt nu een testfilmpje weergegeven. Pas dit aan op: http://doofgewoon.nl/node/231
Het filmpje wordt nu voor elk bezoek weergegeven, om te testen. Zodra je het getest hebt en je ook tevreden bent met het introfilmpje, zetten we het uit voor terugkerende bezoekers. Heropen dan even dit issue.

**Comment by ocrasborn** [comment]
Met de link kom ik op de 'website in ontwikkeling'-welkomstpagina, niet in een edit scherm.

**Comment by signfuse** [comment]
Wel eerst even inloggen. Of www ervoorzetten (je kan 2 sessies hebben, een met www, en een zonder www. Ze herkennen elkaar niet.)
